language: python

python:
  - "2.7"
  - "3.4"
  - "3.8"

install:
  - ./scripts/install_radare2.sh
  - pip install -r python/requirements_ci.txt
  - cd python && ./setup.py install

script:
  - cd test && make tests
